version: '3'
services:

  1kv-core:
    build:
      context: .
      args:
        PACKAGE: core
      dockerfile: ./Dockerfile
    depends_on:
      - redis
    ports:
      - "127.0.0.1:3300:3300"
    networks:
      testing_net:
        ipv4_address: 172.28.1.1

  1kv-gateway:
    build:
      context: .
      args:
        PACKAGE: gateway
      dockerfile: ./Dockerfile
    depends_on:
      - redis
    ports:
      - "127.0.0.1:3301:3301"
    networks:
      testing_net:
        ipv4_address: 172.28.1.2


  1kv-telemetry:
    build:
      context: .
      args:
        PACKAGE: telemetry
      dockerfile: ./Dockerfile
    depends_on:
      - redis
    networks:
      testing_net:
        ipv4_address: 172.28.1.3

  1kv-worker:
    build:
      context: .
      args:
        PACKAGE: worker
      dockerfile: ./Dockerfile
    depends_on:
      - redis
    deploy:
      mode: replicated
      replicas: 4
    networks:
      testing_net:
#        ipv4_address: 172.28.1.3


  mongo:
    image: mongo
    restart: always
    ports:
      - "127.0.0.1:27017:27017"
    networks:
      testing_net:
        ipv4_address: 172.28.1.4
    logging:
      driver: "json-file"
      options:
        max-size: "50m"

  mongo-express:
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
    depends_on:
      - mongo
    ports:
      - "127.0.0.1:8888:8081"
    networks:
      testing_net:
        ipv4_address: 172.28.1.5
    logging:
      driver: "json-file"
      options:
        max-size: "50m"

  redis:
    image: redis:alpine
    expose:
      - "6379"
    volumes:
      - ./redis:/data
    restart: always
    command: ["redis-server", "--bind", "172.28.1.6", "--port", "6379"]
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    networks:
      testing_net:
        ipv4_address: 172.28.1.6


networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
