version: '3'
services:
    1kv-core:
      build:
        context: .
        args:
          PACKAGE: core
        dockerfile: ./Dockerfile-dev
      restart: unless-stopped
      depends_on:
        - redis
      volumes:
        - .:/code
      ports:
        - "127.0.0.1:3300:3300"
      networks:
        testing_net:
          ipv4_address: 172.28.1.7
      logging:
        driver: "json-file"
        options:
          max-size: "50m"

    1kv-gateway:
      build:
        context: .
        args:
          PACKAGE: gateway
        dockerfile: ./Dockerfile-dev
      restart: always
      volumes:
        - .:/code
      ports:
        - "127.0.0.1:3301:3301"
      networks:
        testing_net:
          ipv4_address: 172.28.1.8
      logging:
        driver: "json-file"
        options:
          max-size: "50m"

    1kv-telemetry:
      build:
        context: .
        args:
          PACKAGE: telemetry
        dockerfile: ./Dockerfile-dev
      restart: always
      volumes:
        - .:/code
      networks:
        testing_net:
          ipv4_address: 172.28.1.9
      logging:
        driver: "json-file"
        options:
          max-size: "50m"

    1kv-worker:
      build:
        context: .
        args:
          PACKAGE: worker
        dockerfile: ./Dockerfile-dev
      volumes:
        - .:/code
      deploy:
        mode: replicated
        replicas: 4
      depends_on:
        - redis
      restart: always
      networks:
        testing_net:
#          ipv4_address: 172.28.1.16
      logging:
        driver: "json-file"
        options:
          max-size: "50m"

    mongo:
        image: mongo
        restart: always
        ports:
            - "127.0.0.1:27017:27017"
        networks:
            testing_net:
                ipv4_address: 172.28.1.12
        logging:
          driver: "json-file"
          options:
            max-size: "50m"

    mongo-express:
      image: mongo-express
      environment:
        - ME_CONFIG_MONGODB_SERVER=mongo
        - ME_CONFIG_MONGODB_PORT=27017
        - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
        - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      depends_on:
        - mongo
      ports:
        - "127.0.0.1:8888:8081"
      networks:
        testing_net:
          ipv4_address: 172.28.1.14
      logging:
        driver: "json-file"
        options:
          max-size: "50m"

    redis:
      image: redis:alpine
      ports:
        - "127.0.0.1:6379:6379"
      expose:
        - "6379"
      volumes:
        - ./redis:/data
      restart: always
      command: ["redis-server", "--bind", "172.28.1.13", "--port", "6379"]
      logging:
        driver: "json-file"
        options:
          max-size: "50m"
      networks:
        testing_net:
          ipv4_address: 172.28.1.13

networks:
    testing_net:
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/16
