apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kusama-mongodb-staging
  namespace: argocd
  # finalizers:
  # - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: kusama-1kv-staging
  project: 1kv-backend-staging
  # syncPolicy:
  #   automated:
  #     prune: true
  #     selfHeal: true
  source:
    repoURL: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
    chart: mongodb
    targetRevision: ^14.6.1
    plugin:
      env:
        - name: HELM_VALUES
          value: |
            architecture: standalone
            useStatefulSet: true

            auth:
              enabled: true
              rootPassword: <path:vaults/k8s-community-secrets/items/otv-kusama#mongo-root-password>
              username: <path:vaults/k8s-community-secrets/items/otv-kusama#mongo-username>
              password: <path:vaults/k8s-community-secrets/items/otv-kusama#mongo-password>
              database: <path:vaults/k8s-community-secrets/items/otv-kusama#mongo-db>

            directoryPerDB: true

            tls:
              enabled: false

            systemLogVerbosity: 0
            disableSystemLog: false

            resources:
              limits:
                cpu: 1600m
                memory: 4Gi
              requests:
                cpu: 400m
                memory: 2Gi

            persistence:
              enabled: true

            externalAccess:
              enabled: false

            arbiter:
              enabled: false
          
            metrics:
              enabled: true
              resources:
                limits:
                  cpu: 100m
                  memory: 128Mi
                requests:
                  cpu: 100m
                  memory: 128Mi
---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: polkadot-mongodb-staging
  namespace: argocd
  # finalizers:
  # - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: polkadot-1kv-staging
  project: 1kv-backend-staging
  # syncPolicy:
  #   automated:
  #     prune: true
  #     selfHeal: true
  source:
    repoURL: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
    chart: mongodb
    targetRevision: ^10.31.5
    plugin:
      env:
        - name: HELM_VALUES
          value: |
            clusterDomain: cluster.local
            architecture: {{ .Values.polkadot.db.architecture }}
            useStatefulSet: true

            auth:
              enabled: true
              rootPassword: <path:vaults/k8s-community-secrets/items/otv-polkadot#mongo-root-password>
              username: <path:vaults/k8s-community-secrets/items/otv-polkadot#mongo-username>
              password: <path:vaults/k8s-community-secrets/items/otv-polkadot#mongo-password>
              database: <path:vaults/k8s-community-secrets/items/otv-polkadot#mongo-db>
              {{ if eq .Values.polkadot.db.architecture "replicaset" }}
              replicaSetKey: <path:vaults/k8s-community-secrets/items/otv-polkadot#mongo-rs-key>
              {{ end }}

            directoryPerDB: false

            tls:
              enabled: false
            {{ if eq .Values.polkadot.db.architecture "replicaset" }}
            replicaSetName: rs0
            replicaSetHostnames: true
            {{ end }}

            systemLogVerbosity: 0
            disableSystemLog: false

            annotations: {}
            labels: {}
            replicaCount: 2
            updateStrategy:
              type: RollingUpdate
            podManagementPolicy: OrderedReady
            affinity: {}
            nodeSelector: {}
            podLabels: {}

            podSecurityContext:
              enabled: true
              fsGroup: 1001
              ## sysctl settings
              ## Example:
              ## sysctls:
              ## - name: net.core.somaxconn
              ##   value: "10000"
              ##
              sysctls: []

            containerSecurityContext:
              enabled: true
              runAsUser: 1001
              runAsNonRoot: true

            resources:
              {{- toYaml .Values.polkadot.db.resources | nindent 14 }}

            livenessProbe:
              enabled: true
              initialDelaySeconds: 30
              periodSeconds: 10
              timeoutSeconds: 5
              failureThreshold: 6
              successThreshold: 1
            readinessProbe:
              enabled: true
              initialDelaySeconds: 5
              periodSeconds: 10
              timeoutSeconds: 5
              failureThreshold: 6
              successThreshold: 1

            extraVolumeMounts: []
            extraVolumes: []

            pdb:
              create: false
              minAvailable: 1
              maxUnavailable: 1

            persistence:
              enabled: true
              # storageClass: ""
              accessModes:
                - ReadWriteOnce
              size: {{ .Values.polkadot.db.storage }}
              annotations: {}
              mountPath: /bitnami/mongodb
              subPath: ""
              
            service:
              type: ClusterIP
              ports:
                mongodb: 27017

            externalAccess:
              enabled: false

            arbiter:
              enabled: true
              configuration: ""
              # existingConfigmap:
              annotations: {}
              labels: {}
              affinity: {}
              nodeSelector: {}
              tolerations: []
              podLabels: {}
              podAnnotations: {}

              podSecurityContext:
                enabled: true
                fsGroup: 1001
                ## sysctl settings
                ## Example:
                ## sysctls:
                ## - name: net.core.somaxconn
                ##   value: "10000"
                ##
                sysctls: []

              containerSecurityContext:
                enabled: true
                runAsUser: 1001

              resources:
                limits: 
                  cpu: 100m
                  memory: 128Mi
                requests: 
                  cpu: 100m
                  memory: 128Mi

              livenessProbe:
                enabled: true
                initialDelaySeconds: 30
                periodSeconds: 10
                timeoutSeconds: 5
                failureThreshold: 6
                successThreshold: 1
              readinessProbe:
                enabled: true
                initialDelaySeconds: 5
                periodSeconds: 10
                timeoutSeconds: 5
                failureThreshold: 6
                successThreshold: 1

              pdb:
                create: false
                minAvailable: 1

            serviceAccount:
              create: true

            rbac:
              create: false

            metrics:
              enabled: true
              resources:
                limits: 
                  cpu: 100m
                  memory: 128Mi
                requests: 
                  cpu: 100m
                  memory: 128Mi
              service:
                annotations:
                  prometheus.io/scrape: "true"
                  prometheus.io/port: "9216"
                  prometheus.io/path: "/metrics"
                type: ClusterIP
                port: 9216
              livenessProbe:
                enabled: true
                initialDelaySeconds: 15
                periodSeconds: 5
                timeoutSeconds: 5
                failureThreshold: 3
                successThreshold: 1
              readinessProbe:
                enabled: true
                initialDelaySeconds: 5
                periodSeconds: 5
                timeoutSeconds: 1
                failureThreshold: 3
                successThreshold: 1
