apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kusama-otv-staging-restarter
  namespace: argocd
  # finalizers:
  # - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: kusama-1kv-staging
  project: 1kv-backend-staging
  # syncPolicy:
  #   automated:
  #     prune: true
  #     selfHeal: true
  source:
    repoURL: https://w3f.github.io/helm-charts/
    chart: pod-restarter
    targetRevision: ^v1.0.0
    plugin:
      env:
        - name: HELM_VALUES
          value: |
            schedule: "0 12 * * *"

--- 

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: polkadot-otv-staging-restarter
  namespace: argocd
  # finalizers:
  # - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: polkadot-1kv-staging
  project: 1kv-backend-staging
  # syncPolicy:
  #   automated:
  #     prune: true
  #     selfHeal: true
  source:
    repoURL: https://w3f.github.io/helm-charts/
    chart: pod-restarter
    targetRevision: ^v1.0.0
    plugin:
      env:
        - name: HELM_VALUES
          value: |
            schedule: "0 12 * * *"
